# Generated by Django 6.0.4 on 2026-05-04 20:10

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[utils.validators.validar_cnpj], verbose_name='CNPJ')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
