# Generated by Django 6.0.4 on 2026-05-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('boleto', 'Boleto Bancário'), ('pix', 'PIX')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=15)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID Mercado Pago')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100)),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX (base64)')),
                ('pix_qr_code_texto', models.TextField(blank=True, verbose_name='Código PIX Copia e Cola')),
                ('boleto_url', models.URLField(blank=True, verbose_name='URL do Boleto')),
                ('boleto_barcode', models.CharField(blank=True, max_length=200, verbose_name='Código de Barras')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='candidaturas.candidatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
