# Generated by Django 6.0.4 on 2026-05-04 20:10

import apps.concursos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('orgao', models.CharField(max_length=200, verbose_name='Órgão/Instituição')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('vagas_total', models.PositiveIntegerField(verbose_name='Total de Vagas')),
                ('taxa_inscricao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Inscrição (R$)')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateField(verbose_name='Data de Fechamento')),
                ('data_prova', models.DateField(blank=True, null=True, verbose_name='Data da Prova')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso')], default='rascunho', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Cargo')),
                ('nivel_escolaridade', models.CharField(max_length=100, verbose_name='Nível de Escolaridade')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário (R$)')),
                ('vagas', models.PositiveIntegerField(verbose_name='Vagas')),
                ('vagas_pcd', models.PositiveIntegerField(default=0, verbose_name='Vagas PCD')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='concursos.concurso')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Edital')),
                ('arquivo', models.FileField(upload_to=apps.concursos.models.edital_upload_path, verbose_name='Arquivo (PDF)')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('retificacao', models.BooleanField(default=False, verbose_name='É Retificação?')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editais', to='concursos.concurso')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
