# Generated by Django 6.0.4 on 2026-05-04 20:10

import apps.candidatos.models
import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=apps.candidatos.models.foto_upload_path, verbose_name='Foto')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[utils.validators.validar_cpf], verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('orgao_emissor', models.CharField(max_length=20, verbose_name='Órgão Emissor')),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=200, verbose_name='Nome do Pai')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Mensal (R$)')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('fixo', 'Fixo')], default='celular', max_length=10)),
                ('tem_whatsapp', models.BooleanField(default=False, verbose_name='Tem WhatsApp?')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='candidatos.candidato')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
