# Generated by Django 6.0.4 on 2026-05-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('paga', 'Paga / Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=25)),
                ('numero_inscricao', models.CharField(blank=True, max_length=20, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='candidatos.candidato')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas', to='concursos.cargo')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='concursos.concurso')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-criado_em'],
                'unique_together': {('candidato', 'concurso')},
            },
        ),
    ]
